/**
 * Byte-compatibility with the upstream OptMem tool: the committed fixture
 * `fixtures/optmem-store/` was generated by the reference Python `memo`
 * (init, two notes, one answered nap, one more note), and this suite reads
 * and appends it with the TypeScript store. Regenerate only against upstream
 * `main` and record the upstream commit in the PR when you do.
 */
import { cpSync, mkdtempSync, rmSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import { MemoryStore } from '../src/store.ts'
import { runCommand } from '../src/engine.ts'

const FIXTURE = fileURLToPath(new URL('./fixtures/optmem-store', import.meta.url))

let dir: string
let store: MemoryStore

beforeEach(() => {
  // Operate on a copy: reading never mutates, but an accidental write must
  // never dirty the committed fixture.
  dir = mkdtempSync(join(tmpdir(), 'dsh-memory-interop-'))
  cpSync(FIXTURE, join(dir, 'memory'), { recursive: true })
  store = new MemoryStore(join(dir, 'memory'))
})

afterEach(() => {
  rmSync(dir, { recursive: true, force: true })
})

describe('upstream-generated store', () => {
  it('wakes verbatim: raw memories, ids, and dates from the Python records', async () => {
    expect(await runCommand(store, 'wake')).toBe(
      '#0 2026-08-23 OptMem fixture: first memory, written by the upstream tool\n'
      + '#1 2026-08-23 OptMem fixture: second memory, about tea 茶\n'
      + '#2 2026-08-23 OptMem fixture: third memory stands alone\n'
      + 'You are awake.',
    )
  })

  it('reads the Python-written summary record at its fixed-width offset', async () => {
    expect(store.treeGet({ lo: 0, hi: 2 })).toBe('Two upstream-written fixture memories, one about tea')
  })

  it('recalls across multi-byte records without boundary drift', async () => {
    expect(await runCommand(store, 'recall tea')).toBe(
      '#1 2026-08-23 OptMem fixture: second memory, about tea 茶\n1 match.',
    )
  })

  it('zooms the settled pair into its raw halves', async () => {
    expect(await runCommand(store, 'zoom 0-1')).toBe(
      '#0 2026-08-23 OptMem fixture: first memory, written by the upstream tool\n'
      + '#1 2026-08-23 OptMem fixture: second memory, about tea 茶',
    )
  })

  it('appends a record the upstream tool can read back (verified at fixture creation)', async () => {
    const out = await runCommand(store, 'note "appended by the TypeScript port"')
    expect(out).toMatch(/^Saved as #3\./)
    expect(store.logGet(3).text).toBe('appended by the TypeScript port')
    // The record lands exactly where upstream would put it: offset 3*320.
    expect(store.logLength()).toBe(4)
  })
})
